require "amazon_pa_api/version"
require "amazon_pa_api/extensions"
require "amazon_pa_api/operations/item_lookup"
require "amazon_pa_api/operations/item_search"
require "amazon_pa_api/operations/similarity_lookup"

require "net/http"
require "cgi"
require "openssl"
require "base64"
